dist: trusty
sudo: required
rvm:
  - 2.3.4
before_install:
- node -v
- npm version
install:
- nvm install node 8
- npm install npm
- node -v
- npm install
- npm run deploy
before_script:
- chmod +x ./cibuild
script: "./cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  - provider: s3
    access_key_id: $AWSKEYID
    secret_access_key:
      secure: $AWSSECRET
    bucket: $AWSBUCKET
    skip_cleanup: true
    region: $AWSREGION
    local-dir: _site
    acl: public_read
    on:
      branch: $DEPLOYPRODBRANCH
  - provider: s3
    access_key_id: $AWSDEVKEYID
    secret_access_key: $AWSDEVSECRET
    bucket: $AWSDEVBUCKET
    skip_cleanup: true
    region: $AWSREGION
    local-dir: _site
    acl: public_read
    on:
      branch: $DEPLOYDEVBRANCH
