language: ruby
rvm:
- 2.3.3
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
install:
- sudo pip3 install awscli
before_script:
- chmod +x ./cibuild
script: "./cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
deploy:
  - provider: s3
    access_key_id: $AWSKEYID
    secret_access_key:
      secure: $AWSSECRET
    bucket: $AWSBUCKET
    skip_cleanup: true
    region: $AWSREGION
    local-dir: _site
    acl: public_read
    on:
      branch: $DEPLOYPRODBRANCH
  - provider: s3
    access_key_id: $AWSDEVKEYID
    secret_access_key: $AWSDEVSECRET
    bucket: $AWSDEVBUCKET
    skip_cleanup: true
    region: $AWSREGION
    local-dir: _site
    acl: public_read
    on:
      branch: $DEPLOYDEVBRANCH
