# Site Settings
title: Dynamic Gravity Systems
description: >
  Dynamic Gravity Systems Homepage
baseurl: ""
url: "http://localhost:4000"

# Build Settings
sass:
  sass_dir: _sass
plugins:
  - jekyll-octicons
include: ['_pages']
exclude: ['images/sources', vendor, script, Gemfile, Gemfile.lock, README.md]
kramdown:
  input: GFM
