# Site Settings
title: Dynamic Gravity Systems
description: >
  Dynamic Gravity Systems Homepage
baseurl: ""

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
exclude: ['assets/images/sources', vendor, 'script/', Gemfile, Gemfile.lock, '.idea/', License, README.md,
          'node_modules/', 'package-lock.json', 'webpack.config.js', 'webpack.dev.js', 'webpack.prod.js',
          'LICENSE-Materialize', 'js/src']
markdown: kramdown
kramdown:
  input: GFM

collections:
  - services
