# Site Settings
title: Dynamic Gravity Systems
description: Dynamic Gravity Systems Homepage
baseurl: ""

# Build Settings
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages', '_products', '_tools']
exclude: ['assets/images/sources/', 'assets/raw/', 'vendor', 'script/', 'Gemfile', 'Gemfile.lock', '.idea/', 'LICENSE',
          'README.md', 'node_modules/', 'package-lock.json', 'package.json', 'webpack.common.js', 'webpack.dev.js',
          'webpack.prod.js', 'LICENSE-Materialize', 'js/src', 'build.sh', '_config.yml']
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- excerpt -->"

collections:
  - services
