# Site Settings
title: Dynamic Gravity Systems
description: >
  Dynamic Gravity Systems Homepage
baseurl: ""
url: "http://localhost:4000"

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
exclude: ['images/sources']
kramdown:
  input: GFM
