# Site Settings
title: Dynamic Gravity Systems
description: >
  Dynamic Gravity Systems Homepage
baseurl: ""

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
exclude: ['assets/images/sources', vendor, 'script/', Gemfile, Gemfile.lock, README.md, '.idea/', License, README.md]
markdown: kramdown
kramdown:
  input: GFM

collections:
  - services
