intro: >
  Dynamic Gravity Systems (DgS) specializes in the manufacture and servicing of zero-length spring based, full feedback,
   dynamic gravity meters - for Air, Sea and Land applications.
image-base: /assets/products/
products:
  - name: Airborne Gravity - AT1A
    icon: flight
    icon_color: text-darken-2 blue-grey
    accent: purple
    anchor: airborne
    content: >
      Dynamic Gravity Systems Inc. (DgS) presents its airborne gravity survey system, a robust full feedback zero-length
      spring based gravity meter, with worldwide gravity range. Our new and upgraded systems feature full feedback
      magnetic damping, redesigned and improved platform control, integrated high-performance, temperature-controlled
      electronics, and a simplified user-friendly data display and system control interface.
    image: airborne-meter-1.jpg
    image-alt:
    table: true
    tbl_headers:
    tbl_rows:
      Gravity Range/Specific Force: +/- 1g (1000mGals)
      Sensor Type: Zero-Length Spring
      Resolution: 0.01 milliGals (mGals)
      Static Repeatability: 0.03 mGals
      Dynamic Repeatability: |
        0.25 mGal @ 50,00 mGal horizontal<br>
        0.50 mGal @ 100,000 mGal horizontal<br>
        0.50 mGal @ 100,000 mGal vertical<br>
      Platform Period: 4 Minutes/8 Minutes/INS aided
      Data and GPS recording freq: 10Hz
      INS Platform Control: Optional
      Dimensions (approx): |
        71(l) x 56(w) x 84(h) cm<br>
        28(l) x 22(w) x 33(h) inches
      Weight (approx): |
        80kg / 177lbs<br>
        +25kg / +55lbs with UPS
      Power Consumption: |
        Avg: 60 Watts<br>
        Max: 150 Watts<br>
        Input: 80-265 VAC

  - name: Marine Gravity - AT1M
    icon: directions_boat
    icon_color: blue
    accent: '#6196ed'
    anchor: marine
    content: >
      DgS's Marine Gravity Sensor is based on the same advanced sensor and platform technology as our Airborne
      gravity platform, with a more compact frame. Our Marine gravity solution utilizes a similar custom data-display and
      data collection interface, for easy and robust operation.
    image: marine-meter-4.png
    table: true
    tbl_headers:
    tbl_rows:
      Gravity Range: +/- 1g (200,000 mGals)
      Sensor Type: Zero-Length Spring
      Resolution: 0.01 mGals
      Static Repeatability: 0.03 mGals
      Dynamic Repeatability: |
        0.25 mGal @ 50,00 mGal horizontal<br>
        0.50 mGal @ 100,000 mGal horizontal<br>
        0.25 mGal @ 100,000 mGal vertical<br>
      Platform Period: 4 Minutes/8 Minutes
      Data and GPS recording freq: 10Hz
      INS Platform Control: Optional
      Dimensions (approx): |
        71(l) x 56(w) x 84(h) cm<br>
        28(l) x 22(w) x 33(h) inches
      Weight (approx): |
        80kg / 177lbs<br>
        +25kg / +55lbs with UPS
      Power Consumption: |
        Avg: 60 Watts<br>
        Max: 150 Watts<br>
        Input: 80-265 VAC

  - name: Land Gravity
    icon: landscape
    icon_color: green
    accent: '#84ed61'
    anchor: land
    content: >
      Dynamic Gravity Systems Inc. (DgS) Introduces its newest Advanced Technology to the latest land gravity meter.
      Following in the footsteps of the famous LaCoste and Romberg Model G land meter, DgS has developed the first
      worldwide range, full force feedback land meter using a zero length spring.<br><br><br>
    image: land-meter-1.jpg
    table: true
    tbl_rows:
      Gravity Range: 7000 mGals (Worldwide)
      Sensor Type: Zero Length Metal Spring
      Resolution: 0.005 milliGals (mGal)
      Repeatability: 0.01 - 0.02 mGals
      Accuracy: 0.02 mGals
      Temperature Range: -25deg Celcius to +45deg Celcius
      Drift: < 1.0 mGal per month from factory, < 0.5 mGal/month after aging
      Output: Serial Data Output/Bluetooth
      Power: Lithium Battery
      Dimensions (approx): 20cm x 18cm x 25cm
      Weight (approx): Meter and Battery 4kg + 5kg with Hard Case
      Available Options: Low temperature environment accessories

  - name: AT1-AUV-M
    accent: '#61ede6'
    content: >
      Dynamic Gravity Systems has developed the AT1-AUV-M as a low-cost solution for user that that would like to add a
      dynamic gravity meter for their existing AUV, for underwater marine survey applications. The systems include the Gravity sensor
      and the electronics necessary for acquiring and storing the Gravity horizontal accelerations, sensor temperature,
      and other signals. The AT1-AUV-M has very high stability and low drift, with an excellent Clamp / Un-clamp repeatability.
    details: >
      Gravity is a powerful tool to profile underground structures. Surface ship gravity is an efficient way to collect gravity over a relatively
      large marine region with medium resolution, due to the distance from the sea floor. A sea-floor gravity meter can observe gravity with high
      resolution, but are limited to small areas and quiet sites.
      <br>
      The AT1-AUV-M can allow operators to match the performance of the sea bottom meters, but over a much larger area, through integration
      with your autonomous underwater vehicle (AUV), allowing high-resolution data collection over an area dependent only on your AUV platform.
      Typically, gravity drifts less than 2 mGals/month and 0.5 mGals/month after aging. This sensor hast also  excellent clamp unclamp repeat characteristics, almost comparable with a Land Meter, which allows the meter to be used as a sea bottom surveying meter with  repeatability  better than 0.030 mGals
      The AT-AUV has been designed as a Dynamic Gravity Sensor with with a gravity range 20.000 mGals making the sensor for dynamic Gravity reading. For this application the user needs to provide a suitable gyroscopic stable platform and and positioning.
      A typical repeatability of the dynamic readings is sigma < 0.060 mGal
      <br><br>
    applications: >
    image: at-auv-1.jpg
    image-text: Prototype AT1
    table: true
    tbl_rows:
      Resolution: 0.001 mGals
      Dynamic Repeatability: 0.060 mGals
      Clamp/Unclamp Repeatability: < 0.030 mGals
      Dynamic Range: 10,000 to 20,000
      Data Output Rate: 10Hz
      Data Output Format: Digital (RS-232)
      Dimensions (approx): 32cm x 32cm x 35cm
      Weight (approx): 7kg/15lbs
      Power Consumption: < 50 watts
